name = "coinecta/vesting"
version = "1.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'coinecta/vesting'"

[repository]
user = "coinecta"
project = "vesting"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "main"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "1.1.0"
source = "github"
